### ISSUE TITLE
Exception in thread Thread-3 on client connected

### ISSUE THREAD

**Issue by xteeio** [rena2damas/remote-opencv-streaming-live-video#6]
Any idea whats wrong?

``
New connection accepted.
Closing connection...
Start listening for connections...
New connection accepted.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xxx/Github/remote-opencv-streaming-live-video/streamer.py", line 53, in run
    missing_data = conn.recv(msg_size - len(data))
MemoryError``

**Comment by rd3x** [comment]
Weird, are you trying to start more than one streaming server at the same time or something? Have you checked your system memory consumption when running the scripts?
